apiVersion: v1
kind: Secret
metadata:
  name: orderflow-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: orderflow
  SPRING_DATASOURCE_PASSWORD: orderflow
  POSTGRES_DB: orderflow
  POSTGRES_USER: orderflow
  POSTGRES_PASSWORD: orderflow
